# Generated by Django 5.1.5 on 2025-02-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_category_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(default='17:00', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='occasion',
            field=models.CharField(default='Birthday', max_length=255),
        ),
    ]
